# Generated by Django 6.0.5 on 2026-07-01 23:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurante", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransacaoHistorica",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("numero_mesa", models.PositiveIntegerField()),
                (
                    "data_finalizacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("PIX", "Pix"),
                            ("CARTAO_CREDITO", "Cartão de Crédito"),
                            ("CARTAO_DEBITO", "Cartão de Débito"),
                            ("DINHEIRO", "Dinheiro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(decimal_places=2, max_digits=10, max_length=10),
                ),
                (
                    "estabelecimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transacoes",
                        to="restaurante.estabelecimento",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_finalizacao"],
            },
        ),
        migrations.CreateModel(
            name="ItemTransacaoHistorico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("produto_nome", models.CharField(max_length=255)),
                (
                    "categoria_nome",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "transacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="restaurante.transacaohistorica",
                    ),
                ),
            ],
        ),
    ]
